### ISSUE TITLE
Problems installing 2.4.0

### ISSUE THREAD

**Issue by rsamples** [cqframework/atom_cql_support#15]
I installed the 2.4.0 upgrade and the CQL language server will not start.  Left Atom open over night, closed and reopened several times.  Now unable to uninstall language-cql plugin.

**Comment by lrasmus** [comment]
Same here, I receive the error below in Atom.  I was able to get this to go away by updating from openjdk10 to openjdk11.  Is that required for the new release?

`Error: LinkageError occurred while loading main class org.cqframework.cql.ls.Main java.lang.UnsupportedClassVersionError: org/cqframework/cql/ls/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0 Error: LinkageError occurred while loading main class org.cqframework.cql.ls.Main java.lang.UnsupportedClassVersionError: org/cqframework/cql/ls/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 54.0
`

**Comment by JPercival** [comment]
Yes, JDK 11 is now required. The cql-to-elm translator now uses JDK 11, which is an upstream project that the plugin depends on.

The plugin is supposed to check for the correct java version. 2.4.0 was incorrectly checking for version 8. This been fixed in release 2.4.1 to check for 11.

OpenJDK 11 works well and is free for professional use.
https://adoptopenjdk.net/index.html?variant=openjdk11&jvmVariant=openj9

**Comment by JPercival** [comment]
Turns out many of the institutions we're supporting have not yet moved to Java 11. So we're going back to 8. All of the upstream projects have already been downgraded, so at this point it's a matter of updated the plugin to accept 8 and do some testing. Should happen "soon".
